"""Auto-generated catalog data from dataset/products.xlsx.

ONLY MEAT AND SEAFOOD PRODUCTS ARE INCLUDED.

Do not edit by hand — regenerate with dataset/generate_catalog_data.py.
"""


CATALOG = [
    {"category": "Goat", "slug": "goat", "display_order": 1},
    {"category": "Chicken", "slug": "chicken", "display_order": 2},
    {"category": "Lamb", "slug": "lamb", "display_order": 3},
    {"category": "Seafood", "slug": "seafood", "display_order": 4},
]


PRODUCTS = [
    ('Goat Mixed Cut', 'Goat', '🥩', 14.99, 'lb', 'nonveg', 'Halal goat mixed cut. Sold by the pound. Default: medium pieces.'),
    ('Goat Leg', 'Goat', '🥩', 15.49, 'lb', 'nonveg', 'Halal goat leg. Sold by the pound. Default: medium pieces.'),
    ('Goat Shoulder', 'Goat', '🥩', 15.49, 'lb', 'nonveg', 'Halal goat shoulder. Sold by the pound. Default: medium pieces.'),
    ('Goat Chops', 'Goat', '🥩', 15.49, 'lb', 'nonveg', 'Halal goat chops. Sold by the pound. Trimmed for fry or grill.'),
    ('Goat Kheema', 'Goat', '🥩', 17.49, 'lb', 'nonveg', 'Halal goat kheema. Sold by the pound.'),
    ('Goat Boneless', 'Goat', '🥩', 17.49, 'lb', 'nonveg', 'Halal boneless goat. Sold by the pound. Default: medium pieces.'),
    ('Goat Paya (Burnt & Cut)', 'Goat', '🥩', 10.99, 'lb', 'nonveg', 'Goat paya, burnt and cut. Sold by the pound.'),
    ('Goat Kidney', 'Goat', '🥩', 7.5, 'lb', 'nonveg', 'Halal goat kidney. Sold by the pound.'),
    ('Goat Liver', 'Goat', '🥩', 9.99, 'lb', 'nonveg', 'Halal goat liver (kaleji). Sold by the pound.'),
    ('Goat Head', 'Goat', '🥩', 15.99, 'lb', 'nonveg', 'Goat head. Sold by the pound. Note cut or uncut at checkout.'),
    ('Goat Intestine / Boti', 'Goat', '🥩', 12.49, 'lb', 'nonveg', 'Halal goat intestine / boti. Sold by the pound.'),
    ('Goat Stomach', 'Goat', '🥩', 10.99, 'lb', 'nonveg', 'Halal goat stomach. Sold by the pound.'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'Chicken', '🍗', 13.49, 'bird', 'nonveg', 'Whole bird, skinless, cleaned and cut. Price is per bird. Default: small pieces.'),
    ('Organic Chicken (Skinless, Clean & Cut)', 'Chicken', '🍗', 17.99, 'bird', 'nonveg', 'Organic whole chicken, skinless, cleaned and cut. Price is per bird.'),
    ('Country Chicken (Natu Kodi)', 'Chicken', '🍗', 22.99, 'bird', 'nonveg', 'Country chicken (natu kodi). Price is per bird.'),
    ('Country Chicken (Natu Kodi) — Cut, Turmeric & Burn', 'Chicken', '🍗', 24.99, 'bird', 'nonveg', 'Natu kodi cut, turmeric applied, and burnt. Price is per bird.'),
    ('Chicken Kheema', 'Chicken', '🍗', 7.49, 'lb', 'nonveg', 'Fresh chicken kheema. Sold by the pound. No fillers.'),
    ('Chicken Leg Quarters (Skinless & Cut)', 'Chicken', '🍗', 5.49, 'lb', 'nonveg', 'Skinless leg quarters, cut. Sold by the pound. Default: small pieces.'),
    ('Boneless Chicken Breasts', 'Chicken', '🍗', 6.49, 'lb', 'nonveg', 'Boneless chicken breasts. Sold by the pound. Note curry cut, cubes, or strips at checkout.'),
    ('Boneless Chicken Thighs', 'Chicken', '🍗', 6.49, 'lb', 'nonveg', 'Boneless chicken thighs. Sold by the pound.'),
    ('Chicken Liver', 'Chicken', '🍗', 6.49, 'lb', 'nonveg', 'Chicken liver. Sold by the pound.'),
    ('Lamb Leg/Shoulder', 'Lamb', '🥩', 13.99, 'lb', 'nonveg', 'Lamb. Sold by the pound. Note leg or shoulder at checkout.'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'Seafood', '🐟', 4.5, 'fish', 'nonveg', 'Whole tilapia, frozen, cleaned and gutted. Price is per fish.'),
]


SEARCH_TERMS = [
    ('Goat Mixed Cut', 'goat mixed cut', 'official', 'None'),
    ('Goat Mixed Cut', 'goat', 'alias', 'English'),
    ('Goat Mixed Cut', 'mutton mixed cut', 'alias', 'English'),
    ('Goat Mixed Cut', 'goat curry cut', 'alias', 'English'),
    ('Goat Mixed Cut', 'goat meat', 'alias', 'English'),
    ('Goat Mixed Cut', 'meka mamsam', 'regional', 'Telugu'),
    ('Goat Mixed Cut', 'aadu mamsam', 'regional', 'Tamil'),
    ('Goat Mixed Cut', 'bakra', 'regional', 'Hindi'),
    ('Goat Leg', 'goat leg', 'official', 'None'),
    ('Goat Leg', 'mutton leg', 'alias', 'English'),
    ('Goat Leg', 'goat raan', 'alias', 'English'),
    ('Goat Leg', 'meka kaalu', 'regional', 'Telugu'),
    ('Goat Leg', 'aadu kaal', 'regional', 'Tamil'),
    ('Goat Leg', 'bakre ki raan', 'regional', 'Hindi'),
    ('Goat Shoulder', 'goat shoulder', 'official', 'None'),
    ('Goat Shoulder', 'mutton shoulder', 'alias', 'English'),
    ('Goat Shoulder', 'meka bhujam', 'regional', 'Telugu'),
    ('Goat Shoulder', 'aadu thol', 'regional', 'Tamil'),
    ('Goat Chops', 'goat chops', 'official', 'None'),
    ('Goat Chops', 'mutton chops', 'alias', 'English'),
    ('Goat Chops', 'goat ribs', 'alias', 'English'),
    ('Goat Chops', 'meka chops', 'regional', 'Telugu'),
    ('Goat Kheema', 'goat kheema', 'official', 'None'),
    ('Goat Kheema', 'mutton kheema', 'alias', 'English'),
    ('Goat Kheema', 'keema', 'alias', 'English'),
    ('Goat Kheema', 'meka keema', 'regional', 'Telugu'),
    ('Goat Kheema', 'bakra keema', 'regional', 'Hindi'),
    ('Goat Boneless', 'goat boneless', 'official', 'None'),
    ('Goat Boneless', 'boneless mutton', 'alias', 'English'),
    ('Goat Boneless', 'boneless goat', 'alias', 'English'),
    ('Goat Boneless', 'meka boneless', 'regional', 'Telugu'),
    ('Goat Paya (Burnt & Cut)', 'goat paya', 'official', 'None'),
    ('Goat Paya (Burnt & Cut)', 'mutton paya', 'alias', 'English'),
    ('Goat Paya (Burnt & Cut)', 'paya', 'alias', 'English'),
    ('Goat Paya (Burnt & Cut)', 'meka paya', 'regional', 'Telugu'),
    ('Goat Paya (Burnt & Cut)', 'bakra paya', 'regional', 'Hindi'),
    ('Goat Kidney', 'goat kidney', 'official', 'None'),
    ('Goat Kidney', 'mutton kidney', 'alias', 'English'),
    ('Goat Kidney', 'meka kidney', 'regional', 'Telugu'),
    ('Goat Liver', 'goat liver', 'official', 'None'),
    ('Goat Liver', 'mutton liver', 'alias', 'English'),
    ('Goat Liver', 'kaleji', 'regional', 'Hindi'),
    ('Goat Liver', 'meka liver', 'regional', 'Telugu'),
    ('Goat Head', 'goat head', 'official', 'None'),
    ('Goat Head', 'mutton head', 'alias', 'English'),
    ('Goat Head', 'tala mamsam', 'regional', 'Telugu'),
    ('Goat Head', 'bakra head', 'regional', 'Hindi'),
    ('Goat Intestine / Boti', 'goat intestine', 'official', 'None'),
    ('Goat Intestine / Boti', 'goat boti', 'alias', 'English'),
    ('Goat Intestine / Boti', 'boti', 'alias', 'English'),
    ('Goat Intestine / Boti', 'meka boti', 'regional', 'Telugu'),
    ('Goat Stomach', 'goat stomach', 'official', 'None'),
    ('Goat Stomach', 'mutton stomach', 'alias', 'English'),
    ('Goat Stomach', 'meka stomach', 'regional', 'Telugu'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'whole chicken', 'official', 'None'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'skinless chicken', 'alias', 'English'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'cleaned chicken', 'alias', 'English'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'kodi', 'regional', 'Telugu'),
    ('Whole Chicken (Skinless, Clean & Cut)', 'murgi', 'regional', 'Hindi'),
    ('Organic Chicken (Skinless, Clean & Cut)', 'organic chicken', 'official', 'None'),
    ('Organic Chicken (Skinless, Clean & Cut)', 'organic skinless chicken', 'alias', 'English'),
    ('Organic Chicken (Skinless, Clean & Cut)', 'organic kodi', 'regional', 'Telugu'),
    ('Country Chicken (Natu Kodi)', 'country chicken', 'official', 'None'),
    ('Country Chicken (Natu Kodi)', 'natu kodi', 'regional', 'Telugu'),
    ('Country Chicken (Natu Kodi)', 'country hen', 'alias', 'English'),
    ('Country Chicken (Natu Kodi)', 'desi chicken', 'alias', 'Hindi'),
    ('Country Chicken (Natu Kodi) — Cut, Turmeric & Burn', 'natu kodi cut', 'official', 'None'),
    ('Country Chicken (Natu Kodi) — Cut, Turmeric & Burn', 'burnt natu kodi', 'alias', 'English'),
    ('Country Chicken (Natu Kodi) — Cut, Turmeric & Burn', 'turmeric chicken', 'alias', 'English'),
    ('Country Chicken (Natu Kodi) — Cut, Turmeric & Burn', 'natu kodi kaalchina', 'regional', 'Telugu'),
    ('Chicken Kheema', 'chicken kheema', 'official', 'None'),
    ('Chicken Kheema', 'chicken keema', 'alias', 'English'),
    ('Chicken Kheema', 'minced chicken', 'alias', 'English'),
    ('Chicken Kheema', 'chicken mince', 'alias', 'English'),
    ('Chicken Kheema', 'chicken keema', 'regional', 'Hindi'),
    ('Chicken Leg Quarters (Skinless & Cut)', 'chicken leg quarters', 'official', 'None'),
    ('Chicken Leg Quarters (Skinless & Cut)', 'skinless chicken legs', 'alias', 'English'),
    ('Chicken Leg Quarters (Skinless & Cut)', 'chicken legs', 'alias', 'English'),
    ('Chicken Leg Quarters (Skinless & Cut)', 'chicken leg pieces', 'alias', 'English'),
    ('Boneless Chicken Breasts', 'boneless chicken breast', 'official', 'None'),
    ('Boneless Chicken Breasts', 'chicken breast', 'alias', 'English'),
    ('Boneless Chicken Breasts', 'boneless breast', 'alias', 'English'),
    ('Boneless Chicken Breasts', 'chicken breast pieces', 'alias', 'English'),
    ('Boneless Chicken Thighs', 'boneless chicken thighs', 'official', 'None'),
    ('Boneless Chicken Thighs', 'chicken thighs', 'alias', 'English'),
    ('Boneless Chicken Thighs', 'boneless thighs', 'alias', 'English'),
    ('Chicken Liver', 'chicken liver', 'official', 'None'),
    ('Chicken Liver', 'chicken kaleji', 'alias', 'English'),
    ('Chicken Liver', 'kaleji', 'regional', 'Hindi'),
    ('Chicken Liver', 'kodi liver', 'regional', 'Telugu'),
    ('Lamb Leg/Shoulder', 'lamb', 'official', 'None'),
    ('Lamb Leg/Shoulder', 'lamb leg', 'alias', 'English'),
    ('Lamb Leg/Shoulder', 'lamb shoulder', 'alias', 'English'),
    ('Lamb Leg/Shoulder', 'mutton', 'alias', 'English'),
    ('Lamb Leg/Shoulder', 'lamb meat', 'alias', 'English'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'tilapia', 'official', 'None'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'whole tilapia', 'alias', 'English'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'frozen tilapia', 'alias', 'English'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'cleaned tilapia', 'alias', 'English'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'fish', 'alias', 'English'),
    ('Whole Tilapia (Frozen, Cleaned & Gutted)', 'chepa', 'regional', 'Telugu'),
]
